default["lampbase"]["apache_allow_override"] = "All"
default["lampbase"]["apache_docroot"]        = "/vagrant/public"
default["lampbase"]["apache_options"]        = "FollowSymLinks"

default["lampbase"]["db_name"]      = "changeme"
default["lampbase"]["db_username"]  = "changeme"
default["lampbase"]["db_password"]  = "changeme"
default["lampbase"]["db_password"]  = "changeme"
default["lampbase"]["db_host"]      = "%"
default["lampbase"]["db_encoding"]  = "utf8"
default["lampbase"]["db_collation"] = "utf8_unicode_ci"
